### ISSUE TITLE
Package dependencies

### ISSUE THREAD

**Issue by RaoulWolf** [NIVANorge/aquamonitR#3]
Starting to investigate the code I first stumbled across the necessary packages and their dependencies:

* {httr}: **5** dependencies
* {getPass}: **1** dependency
* {jsonlite}: **0** dependencies
* {data.table}: **0** dependencies
* {dplyr}: **12** dependencies

Keeping in mind that `aquamonitR` *could* be turned into an R package, it may be sensible to consider if all of these dependencies are necessary or if better (= lighter) alternatives are available. This is to keep the additional dependencies as slim as possible, which increases the chances of a package working "straight out the box". It also makes maintenance of the functionalities easier, because less dependencies can be broken 😉 

First the easy picks: {getPass} and {jsonlite} should be kept, as they offer crucial (and simple) functionalities with virtually no dependencies. (I didn't even know about {getPass}, but I like it a lot! I have been using {keyring} for a long time.)

{httr} is essential as well, but could be replaced with the (dependency-free) {curl}, which {httr} calls under the hood anyway. The downside is some of the code would need to be slightly rewritten. (I have experience with this.)

I think {dplyr} can be removed, as the few {dplyr} functions I've seen (e.g., `select()`) can easily be rewritten in base R. 

I'm not entirely sure what {data.table} brings to the, huh, table. I assume the idea is to handle the tables faster, but I do not see any {data.table}-y code snippets appearing. As installation of {data.table} can be tricky at times (don't @ me), it may be worth it to drop this dependency. 

These measures would reduce the additional dependencies from currently 18 to a single dependency, which would be {rstudioapi} for {getPass}. 

Again, these are thoughts for an eventual package and its maintainability and longevity. The correct functionality seems to be in place already 😃

**Comment by JamesSample** [comment]
This all sounds good, @RaoulWolf ! 

I certainly agree about `data.table` and `dplyr`. They're only included because I had to Google a bit to find ways of (i) efficiently concatenating multiple dataframes with - potentially - different columns names (`bind_rows`) and (ii) renaming and subsetting dataframe columns. Methods involving `data.table` and `dplyr` came up first on StackOverflow so I used them, but basic R alternatives would be very welcome.

I found it quite fiddly to get the syntax correct for `httr` (mostly regarding modifying the "headers" to pass the Aquamonitor cookies correctly). If you have suggestions for how to rewrite these calls using `curl` I agree that would be an improvement.

Thanks for taking a look!

**Comment by RaoulWolf** [comment]
Opened a PR for the pure {curl} version of `get_json()` and `post_json()` here: https://github.com/NIVANorge/aquamonitR/pull/4 

It works for me, but that's not saying much 😉 

I can take a look at the relevant {dplyr} and {data.table} tidbits tomorrow.

**Comment by JamesSample** [comment]
Closed by 926abba475da9d88c346f106f08d1d37cc4c353a.
